#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/65fdc915-34dc-4256-8247-d07dcdd943f4

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float loudness;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <math.h>

const int soundPin = A0;
const int baudRate = 115200;
Client& client = ArduinoIoTPreferredConnection.getClient();

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  if (isnan(threshold)) {
    Serial.println("threshold undefined, Setting to default value ");
    threshold = 0.0f;
  }
}

const int passes = 1;
float getCurrentLoudness() {
  float sensorValue = 0;
  for (int i = 0; i < passes; i++) {
    sensorValue += analogRead(soundPin);
    delay(1);
  }
  return sensorValue / (1023.0f * (float)passes);
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  loudness = getCurrentLoudness();
  if (loudness > threshold) {
    Serial.println(loudness);
    isVoliation = true; 
  } else {
    isVoliation = false;
  }
}

void onThresholdChange() {
  Serial.println("New threshold set ");
  Serial.println(threshold);
}
